config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  namespace :admin do
    resources :categories
    resources :images
  end

  resources :users do
    resources :ideas
  end

  resources :categories, only: [:index, :show]
  resources :images, only: [:index, :show]

  controller :sessions do
    get '/login' => :new
    post '/login' => :create
    get '/logout' => :destroy #this is the same as using delete and then having the method: :delete on the actual link
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: { case_sensitive: false}, presence: true
  validates :description, presence: true
  has_many :ideas, dependent: :destroy
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :name, :description, presence: true
  belongs_to :user
  belongs_to :category
  has_many :idea_images, dependent: :destroy
  has_many :images, through: :idea_images
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  validates :name, presence: true
  validates :url, uniqueness: true, presence: true
  has_many :idea_images, dependent: :destroy
  has_many :ideas, through: :idea_images

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, uniqueness: { case_sensitive: false }, presence: true
  has_secure_password
  has_many :ideas

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :check_admin

  def check_admin
    if !current_user.admin?
      render file: "#{Rails.root}/public/404", layout: false, status: :not_found
    end
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  before_action :find_category, only: [:show, :edit, :update, :destroy]
  
  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def update
    @category.update(category_params)
    redirect_to admin_category_path(@category)
  end

  def create
    category = Category.new(category_params)
    if category.save
      flash[:success] = "Successfully created new category."
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def find_category
    @category = Category.find(params[:id])
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  before_action :find_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:success] = "Successfully created #{@image.name} image."
      redirect_to admin_images_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @image.update(image_params)
    redirect_to admin_image_path(@image)
  end

  def destroy
    @image.destroy
    redirect_to admin_images_path
  end

  private

  def image_params
    params.require(:image).permit(:name, :url)
  end

  def find_image
    @image = Image.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_logged_in
    if current_user.nil?
      flash[:danger] = "Login to visit that page."
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :check_logged_in, only: :show

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @ideas = @category.ideas.where(user_id: current_user.id)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :check_logged_in
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :load_images_and_categories, only: [:new, :edit]

  def index
    @ideas = current_user.ideas
  end

  def new
    @idea = current_user.ideas.new
  end

  def show
  end

  def create
    @idea = current_user.ideas.new(idea_params)
    if @idea.save
      redirect_to user_idea_path(current_user, @idea)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @idea.update(idea_params)
    redirect_to user_idea_path(current_user, @idea)
  end

  def destroy
    @idea.destroy
    redirect_to user_ideas_path(current_user)
  end

  private

  def idea_params
    params.require(:idea).permit(:name, :description, :category_id, image_ids:[])
  end

  def find_idea
    @idea = Idea.find(params[:id])
  end

  def load_images_and_categories
    @categories = Category.all
    @images = Image.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end

  def show
    @image = Image.find(params[:id])
    @ideas = @image.ideas.where(user_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.clear
    flash[:success] = "Logged Out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_logged_in, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Thanks for signing up!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:danger] = "Invalid email/password"
      render :new
    end
  end

  def show
    @ideas = current_user.ideas
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.submit class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<h2 class='headline'>Edit <%= "#{@category.name}" %></h2>

<%= render partial: 'form' %>

app/views/admin/categories/index.html.erb
<h2 class='headline'>All Categories</h2>

<h3><%= link_to "Create a new category", new_admin_category_path %></h3>
<section class='categories'>
  <% @categories.each do |category| %>
    <h4><%= link_to "#{category.name}", admin_category_path(category) %></h4>
    <p><%= button_to "Delete this category", admin_category_path(category), method: :delete, class: "btn-primary btn-xs btn-delete" %></p>
  <% end %>
</section>

app/views/admin/categories/new.html.erb
<h2 class='headline'>Create A New Category</h2>

<%= render partial: 'form' %>

app/views/admin/categories/show.html.erb
<h2 class='headline'><%= @category.name %></h2>

<p><%= @category.description %></p>

app/views/admin/images/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @image] do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :url %>
    <%= f.text_area :url %>

    <%= f.submit class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/admin/images/edit.html.erb
<%= render partial: 'form' %>

app/views/admin/images/index.html.erb
<h2 class='headline'>All Images</h2>

<h3><%= link_to "Create a new image", new_admin_image_path %></h3>

<section class='images'>
  <% @images.each do |image|  %>
  <p><%= image.name %></p>
  <%= image_tag(image.url, size: "150x100", alt: image.name ) %>
  <p><%= button_to "Delete this image", admin_image_path(image), method: :delete, class: "btn-primary btn-xs btn-delete" %></p>
  <% end %>
</section>

app/views/admin/images/new.html.erb
<%= form_for [:admin, @image] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :url %>
  <%= f.text_area :url %>

  <%= f.submit %>
  
<% end %>

app/views/admin/images/show.html.erb
<p><%= @image.name %></p>
<%= image_tag(@image.url, size: "450x300", alt: @image.name ) %>

app/views/categories/index.html.erb
<h2 class='headline'>All Categories</h2>

<% @categories.each do |category| %>
  <h4 class='category'><%= link_to "#{category.name}", category_path(category) %></h4>
<% end %>

app/views/categories/show.html.erb
<%= link_to "All Categories", categories_path %>

<h2 class='headline'><%= @category.name %></h2>

<p>Description: <%= @category.description %></p>

<section class='ideas'>
  <% @ideas.each do |idea| %>
  <li><%= link_to "#{idea.name}", user_idea_path(current_user, idea) %></li>
  <% end %>
</section>

app/views/ideas/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [current_user, @idea] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>

    <%= f.label :description %>
    <%= f.text_area :description %><br><br>

    <%= f.collection_select(:category_id, @categories, :id, :name) %><br><br>

    <%= f.label "Image" %><br />
    <%= f.collection_check_boxes :image_ids, @images, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>

    <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/ideas/edit.html.erb
<h2 class='headline'> Edit <%= @idea.name %></h2>

<section class='form-container'>
  <%= render partial: 'form' %>
</section>

app/views/ideas/index.html.erb
<header>
  <%= link_to "Back to #{current_user.name}", user_path(current_user) %>
</header>

<h2 class='headline'>Ideas for <%="#{current_user.name}"%></h2>
<h4><%= link_to "Create a new idea", new_user_idea_path(current_user) %></h4>

<% @ideas.each do |idea| %>
  <section class='ideas'>
    <p><%= link_to "#{idea.name}", user_idea_path(current_user, idea) %>: <%= idea.description %></p>
  </section>
<% end %>

app/views/ideas/new.html.erb
<h2 class='headline'> Create a new idea for <%="#{current_user.name}"%>!</h2>

<section class='form-container'>
  <%= render partial: 'form' %>
</section>

app/views/ideas/show.html.erb
<header>
  <%= link_to "Back to #{current_user.name}", user_path(current_user) %>
</header>

<h2 class='headline'> <%= @idea.name %></h2>
<p><%= @idea.description %></p>
<p>Category: <%= @idea.category.name %></p>

<% @idea.images.each do |image| %>
  <%=image_tag(image.url, class: "idea-image")%><br><br>
<% end %>

<%= link_to "Edit this idea", edit_user_idea_path(current_user, @idea) %><br>
<%= link_to "Delete this idea", user_idea_path(current_user, @idea), method: :delete %>

app/views/images/index.html.erb
<h2 class='headline'>All Images</h2>

<section class='images'>
  <% @images.each do |image|  %>
    <%= image_tag(image.url, size: "150x100") %>
    <%= link_to "#{image.name}", image_path(image) %><br><br>
  <% end %>
</section>

app/views/images/show.html.erb
<h2 class='headline'><%= @image.name %></h2>

<%= image_tag(@image.url, size: "400x300") %><br><br>
<h4>Ideas for <%= @image.name %></h4>
<% @ideas.each do |idea| %>
  <%= link_to "#{idea.name}", user_idea_path(current_user, idea) %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
        <% if !current_user %>
        <li><%= link_to "Log in", login_path %></li>
        <% elsif current_user %>
        <li><%= link_to "Images", images_path %></li>
        <li><%= link_to "Ideas", user_ideas_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header_admin.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Categories", admin_categories_path %></li>
        <li><%= link_to "Images", admin_images_path %></li>
        <% if !current_user %>
        <li><%= link_to "Log in", login_path %></li>
        <% elsif current_user %>
        <li><%= link_to "Ideas", user_ideas_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <% if current_user && current_user.admin? %>
    <%= render 'layouts/header_admin' %>
    <% elsif %>
    <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.submit 'Sign up!', class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h2 class='headline'>Create a new user</h2>

<section class='form-container'>
  <%= render partial: 'form' %>
</section>

app/views/users/show.html.erb
<h2 class='headline'>Welcome, <%= current_user.name %>!</h2>

<h4><%= link_to "Create a new idea", new_user_idea_path(current_user) %></h4>

<% @ideas.each do |idea| %>
  <section class='ideas'>
    <p><%= link_to "#{idea.name}", user_idea_path(current_user, idea) %>: <%= idea.description %></p>
  </section>
<% end %>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to IdeaBox!</h1>
  <br><br>
  <% if !current_user %>
    <%= link_to "Sign up!", new_user_path, class: "btn btn-lg btn-primary" %>
  <% elsif current_user %>
    <%= link_to "My Ideas", user_ideas_path(current_user), class: "btn btn-lg btn-primary" %>
    <%= link_to "Categories", categories_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Create a New Idea", new_user_idea_path(current_user), class: "btn btn-lg btn-primary" %>
  <% end %>
</div>